package com.sijan.bookandreadingtracker.data.repository

import com.sijan.bookandreadingtracker.data.local.BookDao
import com.sijan.bookandreadingtracker.data.local.BookEntity
import com.sijan.bookandreadingtracker.data.remote.GoogleBooksApiService
import com.sijan.bookandreadingtracker.data.remote.dto.BookItemDto
import com.sijan.bookandreadingtracker.domain.repository.BookRepository
import kotlinx.coroutines.flow.Flow
import javax.inject.Inject

class BookRepositoryImpl @Inject constructor(
    private val bookDao: BookDao,
    private val apiService: GoogleBooksApiService
) : BookRepository {

    override fun getAllBooks(): Flow<List<BookEntity>> {
        return bookDao.getAllBooks()
    }

    override fun getLibraryBooks(): Flow<List<BookEntity>> {
        return bookDao.getLibraryBooks()
    }

    override fun getCurrentReads(): Flow<List<BookEntity>> {
        return bookDao.getCurrentReads()
    }

    override fun getFinishedBooks(): Flow<List<BookEntity>> {
        return bookDao.getFinishedBooks()
    }

    override suspend fun getBookById(id: Long): BookEntity? {
        return bookDao.getBookById(id)
    }

    override fun observeBookById(id: Long): Flow<BookEntity?> {
        return bookDao.observeBookById(id)
    }

    override suspend fun insertBook(book: BookEntity): Long {
        return bookDao.insertBook(book)
    }

    override suspend fun updateBook(book: BookEntity) {
        bookDao.updateBook(book)
    }

    override suspend fun deleteBook(book: BookEntity) {
        bookDao.deleteBook(book)
    }

    override suspend fun deleteBookById(id: Long) {
        bookDao.deleteBookById(id)
    }

    override suspend fun updateReadingProgress(bookId: Long, pagesRead: Int) {
        bookDao.updateReadingProgress(bookId, pagesRead)
    }

    override suspend fun updatePersonalNote(bookId: Long, note: String) {
        bookDao.updatePersonalNote(bookId, note)
    }

    override suspend fun addToLibrary(bookId: Long) {
        bookDao.updateLibraryStatus(bookId, true)
    }

    override suspend fun removeFromLibrary(bookId: Long) {
        bookDao.updateLibraryStatus(bookId, false)
    }

    override fun getFinishedBooksCount(): Flow<Int> {
        return bookDao.getFinishedBooksCount()
    }

    override fun getTotalPagesRead(): Flow<Int> {
        return bookDao.getTotalPagesRead()
    }

    override suspend fun searchRemoteBooks(query: String): Result<List<BookEntity>> {
        return try {
            val response = apiService.searchBooks(query)
            val books = response.items?.map { it.toBookEntity() } ?: emptyList()
            Result.success(books)
        } catch (e: Exception) {
            Result.failure(e)
        }
    }

    override suspend fun getRecommendedBooks(): Result<List<BookEntity>> {
        return try {
            val response = apiService.getRecommendedBooks()
            val books = response.items?.map { it.toBookEntity() } ?: emptyList()
            Result.success(books)
        } catch (e: Exception) {
            Result.failure(e)
        }
    }

    private fun BookItemDto.toBookEntity(): BookEntity {
        return BookEntity(
            id = 0, // Auto-generated by Room when inserted
            title = volumeInfo.title ?: "Unknown Title",
            author = volumeInfo.authors?.joinToString(", ") ?: "Unknown Author",
            description = volumeInfo.description ?: "No description available",
            coverUrl = volumeInfo.imageLinks?.thumbnail?.replace("http://", "https://") ?: "",
            publishedDate = volumeInfo.publishedDate ?: "",
            rating = volumeInfo.averageRating ?: 0f,
            pageCount = volumeInfo.pageCount ?: 0,
            pdfUrl = volumeInfo.previewLink ?: "",
            isInLibrary = false,
            pagesRead = 0,
            personalNote = ""
        )
    }
}

