package com.sijan.bookandreadingtracker.data.local

import androidx.room.Room
import androidx.test.core.app.ApplicationProvider
import androidx.test.ext.junit.runners.AndroidJUnit4
import kotlinx.coroutines.flow.first
import kotlinx.coroutines.test.runTest
import org.junit.After
import org.junit.Assert.*
import org.junit.Before
import org.junit.Test
import org.junit.runner.RunWith

@RunWith(AndroidJUnit4::class)
class BookDaoTest {

    private lateinit var database: AppDatabase
    private lateinit var bookDao: BookDao

    private val sampleBook1 = BookEntity(
        id = 1L,
        title = "Test Book 1",
        author = "Author One",
        description = "Description for book 1",
        coverUrl = "https://example.com/cover1.jpg",
        publishedDate = "2023",
        rating = 4.5f,
        pageCount = 300,
        pdfUrl = "https://example.com/book1.pdf",
        isInLibrary = true,
        pagesRead = 150,
        personalNote = "Great book"
    )

    private val sampleBook2 = BookEntity(
        id = 2L,
        title = "Test Book 2",
        author = "Author Two",
        description = "Description for book 2",
        coverUrl = "https://example.com/cover2.jpg",
        publishedDate = "2024",
        rating = 4.0f,
        pageCount = 250,
        pdfUrl = "https://example.com/book2.pdf",
        isInLibrary = true,
        pagesRead = 250, // Finished
        personalNote = ""
    )

    private val sampleBook3 = BookEntity(
        id = 3L,
        title = "Test Book 3",
        author = "Author Three",
        description = "Description for book 3",
        coverUrl = "https://example.com/cover3.jpg",
        publishedDate = "2025",
        rating = 3.5f,
        pageCount = 400,
        pdfUrl = "",
        isInLibrary = false, // Not in library
        pagesRead = 0,
        personalNote = ""
    )

    private val sampleBook4 = BookEntity(
        id = 4L,
        title = "Test Book 4",
        author = "Author Four",
        description = "Description for book 4",
        coverUrl = "https://example.com/cover4.jpg",
        publishedDate = "2024",
        rating = 5.0f,
        pageCount = 500,
        pdfUrl = "https://example.com/book4.pdf",
        isInLibrary = true,
        pagesRead = 0, // In library but not started
        personalNote = ""
    )

    @Before
    fun setUp() {
        // Create in-memory database
        database = Room.inMemoryDatabaseBuilder(
            ApplicationProvider.getApplicationContext(),
            AppDatabase::class.java
        )
            .allowMainThreadQueries() // Only for testing
            .build()

        bookDao = database.bookDao()
    }

    @After
    fun tearDown() {
        database.close()
    }

    // ==================== INSERT TESTS ====================

    @Test
    fun insertBook_insertsBookSuccessfully() = runTest {
        // When
        val insertedId = bookDao.insertBook(sampleBook1)

        // Then
        assertTrue(insertedId > 0)
        val books = bookDao.getAllBooks().first()
        assertEquals(1, books.size)
        assertEquals(sampleBook1.title, books[0].title)
    }

    @Test
    fun insertBook_replacesExistingBookOnConflict() = runTest {
        // Given
        bookDao.insertBook(sampleBook1)

        // When - Insert with same ID but different data
        val updatedBook = sampleBook1.copy(title = "Updated Title")
        bookDao.insertBook(updatedBook)

        // Then
        val books = bookDao.getAllBooks().first()
        assertEquals(1, books.size)
        assertEquals("Updated Title", books[0].title)
    }

    @Test
    fun insertBooks_insertsMultipleBooksSuccessfully() = runTest {
        // When
        val booksList = listOf(sampleBook1, sampleBook2, sampleBook3)
        bookDao.insertBooks(booksList)

        // Then
        val books = bookDao.getAllBooks().first()
        assertEquals(3, books.size)
    }

    @Test
    fun insertBook_withAutoGeneratedId_assignsId() = runTest {
        // Given - Book with ID 0 (auto-generate)
        val bookWithoutId = sampleBook1.copy(id = 0L)

        // When
        val generatedId = bookDao.insertBook(bookWithoutId)

        // Then
        assertTrue(generatedId > 0)
        val retrievedBook = bookDao.getBookById(generatedId)
        assertNotNull(retrievedBook)
        assertEquals(bookWithoutId.title, retrievedBook?.title)
    }

    // ==================== UPDATE TESTS ====================

    @Test
    fun updateBook_updatesBookSuccessfully() = runTest {
        // Given
        bookDao.insertBook(sampleBook1)

        // When
        val updatedBook = sampleBook1.copy(
            title = "Updated Title",
            pagesRead = 200,
            personalNote = "Updated note"
        )
        bookDao.updateBook(updatedBook)

        // Then
        val book = bookDao.getBookById(1L)
        assertNotNull(book)
        assertEquals("Updated Title", book?.title)
        assertEquals(200, book?.pagesRead)
        assertEquals("Updated note", book?.personalNote)
    }

    @Test
    fun updateReadingProgress_updatesProgressSuccessfully() = runTest {
        // Given
        bookDao.insertBook(sampleBook1)

        // When
        bookDao.updateReadingProgress(1L, 250)

        // Then
        val book = bookDao.getBookById(1L)
        assertEquals(250, book?.pagesRead)
    }

    @Test
    fun updatePersonalNote_updatesNoteSuccessfully() = runTest {
        // Given
        bookDao.insertBook(sampleBook1)

        // When
        bookDao.updatePersonalNote(1L, "New personal note")

        // Then
        val book = bookDao.getBookById(1L)
        assertEquals("New personal note", book?.personalNote)
    }

    @Test
    fun updateLibraryStatus_updatesStatusSuccessfully() = runTest {
        // Given
        bookDao.insertBook(sampleBook3) // Not in library

        // When
        bookDao.updateLibraryStatus(3L, true)

        // Then
        val book = bookDao.getBookById(3L)
        assertTrue(book?.isInLibrary ?: false)
    }

    // ==================== DELETE TESTS ====================

    @Test
    fun deleteBook_deletesBookSuccessfully() = runTest {
        // Given
        bookDao.insertBook(sampleBook1)
        bookDao.insertBook(sampleBook2)

        // When
        bookDao.deleteBook(sampleBook1)

        // Then
        val books = bookDao.getAllBooks().first()
        assertEquals(1, books.size)
        assertEquals(sampleBook2.title, books[0].title)
    }

    @Test
    fun deleteBookById_deletesBookSuccessfully() = runTest {
        // Given
        bookDao.insertBook(sampleBook1)
        bookDao.insertBook(sampleBook2)

        // When
        bookDao.deleteBookById(1L)

        // Then
        val books = bookDao.getAllBooks().first()
        assertEquals(1, books.size)
        assertEquals(sampleBook2.title, books[0].title)

        val deletedBook = bookDao.getBookById(1L)
        assertNull(deletedBook)
    }

    @Test
    fun deleteBook_withNonExistentBook_doesNotThrowError() = runTest {
        // Given
        bookDao.insertBook(sampleBook1)

        // When - Delete book that doesn't exist
        bookDao.deleteBook(sampleBook2)

        // Then
        val books = bookDao.getAllBooks().first()
        assertEquals(1, books.size)
    }

    // ==================== GET ALL BOOKS TESTS ====================

    @Test
    fun getAllBooks_returnsEmptyListWhenNoBooks() = runTest {
        // When
        val books = bookDao.getAllBooks().first()

        // Then
        assertTrue(books.isEmpty())
    }

    @Test
    fun getAllBooks_returnsAllBooksIncludingNonLibrary() = runTest {
        // Given
        bookDao.insertBooks(listOf(sampleBook1, sampleBook2, sampleBook3))

        // When
        val books = bookDao.getAllBooks().first()

        // Then
        assertEquals(3, books.size)
        assertTrue(books.any { !it.isInLibrary }) // Contains non-library book
    }

    @Test
    fun getAllBooks_returnsInInsertionOrder() = runTest {
        // Given
        bookDao.insertBook(sampleBook1)
        bookDao.insertBook(sampleBook2)
        bookDao.insertBook(sampleBook3)

        // When
        val books = bookDao.getAllBooks().first()

        // Then
        assertEquals(3, books.size)
        assertEquals(1L, books[0].id)
        assertEquals(2L, books[1].id)
        assertEquals(3L, books[2].id)
    }

    // ==================== GET LIBRARY BOOKS TESTS ====================

    @Test
    fun getLibraryBooks_returnsOnlyBooksInLibrary() = runTest {
        // Given
        bookDao.insertBooks(listOf(sampleBook1, sampleBook2, sampleBook3, sampleBook4))

        // When
        val libraryBooks = bookDao.getLibraryBooks().first()

        // Then
        assertEquals(3, libraryBooks.size) // Book 3 is not in library
        assertTrue(libraryBooks.all { it.isInLibrary })
        assertTrue(libraryBooks.none { it.id == 3L })
    }

    @Test
    fun getLibraryBooks_returnsEmptyWhenNoLibraryBooks() = runTest {
        // Given
        bookDao.insertBook(sampleBook3) // Not in library

        // When
        val libraryBooks = bookDao.getLibraryBooks().first()

        // Then
        assertTrue(libraryBooks.isEmpty())
    }

    @Test
    fun getLibraryBooks_updatesWhenLibraryStatusChanges() = runTest {
        // Given
        bookDao.insertBook(sampleBook3) // Not in library

        // When - Add to library
        bookDao.updateLibraryStatus(3L, true)
        val libraryBooks = bookDao.getLibraryBooks().first()

        // Then
        assertEquals(1, libraryBooks.size)
        assertEquals(3L, libraryBooks[0].id)
    }

    // ==================== GET FINISHED BOOKS TESTS ====================

    @Test
    fun getFinishedBooks_returnsOnlyFinishedBooks() = runTest {
        // Given
        bookDao.insertBooks(listOf(sampleBook1, sampleBook2, sampleBook3, sampleBook4))

        // When
        val finishedBooks = bookDao.getFinishedBooks().first()

        // Then
        assertEquals(1, finishedBooks.size)
        assertEquals(2L, finishedBooks[0].id) // Book 2 is finished (250/250 pages)
        assertTrue(finishedBooks[0].pagesRead >= finishedBooks[0].pageCount)
    }

    @Test
    fun getFinishedBooks_excludesNotStartedBooks() = runTest {
        // Given
        bookDao.insertBook(sampleBook4) // In library but not started

        // When
        val finishedBooks = bookDao.getFinishedBooks().first()

        // Then
        assertTrue(finishedBooks.isEmpty())
    }

    @Test
    fun getFinishedBooks_excludesCurrentlyReading() = runTest {
        // Given
        bookDao.insertBook(sampleBook1) // Currently reading (150/300)

        // When
        val finishedBooks = bookDao.getFinishedBooks().first()

        // Then
        assertTrue(finishedBooks.isEmpty())
    }

    @Test
    fun getFinishedBooks_excludesNonLibraryBooks() = runTest {
        // Given
        val finishedNonLibraryBook = sampleBook3.copy(pagesRead = 400) // Not in library but finished
        bookDao.insertBook(finishedNonLibraryBook)

        // When
        val finishedBooks = bookDao.getFinishedBooks().first()

        // Then
        assertTrue(finishedBooks.isEmpty())
    }

    @Test
    fun getFinishedBooks_includesBooksReadMoreThanPageCount() = runTest {
        // Given - Book read more pages than page count (edge case)
        val overreadBook = sampleBook1.copy(pagesRead = 350, pageCount = 300)
        bookDao.insertBook(overreadBook)

        // When
        val finishedBooks = bookDao.getFinishedBooks().first()

        // Then
        assertEquals(1, finishedBooks.size)
    }

    // ==================== GET CURRENT READS TESTS ====================

    @Test
    fun getCurrentReads_returnsOnlyCurrentlyReadingBooks() = runTest {
        // Given
        bookDao.insertBooks(listOf(sampleBook1, sampleBook2, sampleBook3, sampleBook4))

        // When
        val currentReads = bookDao.getCurrentReads().first()

        // Then
        assertEquals(1, currentReads.size)
        assertEquals(1L, currentReads[0].id) // Book 1 is currently reading (150/300)
        assertTrue(currentReads[0].pagesRead > 0)
        assertTrue(currentReads[0].pagesRead < currentReads[0].pageCount)
    }

    @Test
    fun getCurrentReads_excludesNotStartedBooks() = runTest {
        // Given
        bookDao.insertBook(sampleBook4) // In library but not started

        // When
        val currentReads = bookDao.getCurrentReads().first()

        // Then
        assertTrue(currentReads.isEmpty())
    }

    @Test
    fun getCurrentReads_excludesFinishedBooks() = runTest {
        // Given
        bookDao.insertBook(sampleBook2) // Finished book

        // When
        val currentReads = bookDao.getCurrentReads().first()

        // Then
        assertTrue(currentReads.isEmpty())
    }

    @Test
    fun getCurrentReads_excludesNonLibraryBooks() = runTest {
        // Given
        val readingNonLibraryBook = sampleBook3.copy(pagesRead = 100) // Not in library
        bookDao.insertBook(readingNonLibraryBook)

        // When
        val currentReads = bookDao.getCurrentReads().first()

        // Then
        assertTrue(currentReads.isEmpty())
    }

    @Test
    fun getCurrentReads_updatesWhenProgressChanges() = runTest {
        // Given
        bookDao.insertBook(sampleBook4) // Not started

        // When - Start reading
        bookDao.updateReadingProgress(4L, 50)
        val currentReads = bookDao.getCurrentReads().first()

        // Then
        assertEquals(1, currentReads.size)
        assertEquals(4L, currentReads[0].id)
    }

    @Test
    fun getCurrentReads_removesWhenBookFinished() = runTest {
        // Given
        bookDao.insertBook(sampleBook1) // Currently reading

        // When - Finish the book
        bookDao.updateReadingProgress(1L, 300)
        val currentReads = bookDao.getCurrentReads().first()

        // Then
        assertTrue(currentReads.isEmpty())

        // Verify it's in finished books
        val finishedBooks = bookDao.getFinishedBooks().first()
        assertEquals(1, finishedBooks.size)
    }

    // ==================== GET BOOK BY ID TESTS ====================

    @Test
    fun getBookById_returnsCorrectBook() = runTest {
        // Given
        bookDao.insertBooks(listOf(sampleBook1, sampleBook2, sampleBook3))

        // When
        val book = bookDao.getBookById(2L)

        // Then
        assertNotNull(book)
        assertEquals(2L, book?.id)
        assertEquals(sampleBook2.title, book?.title)
    }

    @Test
    fun getBookById_returnsNullForNonExistentBook() = runTest {
        // Given
        bookDao.insertBook(sampleBook1)

        // When
        val book = bookDao.getBookById(999L)

        // Then
        assertNull(book)
    }

    @Test
    fun observeBookById_emitsUpdatesWhenBookChanges() = runTest {
        // Given
        bookDao.insertBook(sampleBook1)

        // When - Update the book
        val updatedBook = sampleBook1.copy(title = "Updated Title")
        bookDao.updateBook(updatedBook)

        // Then
        val observedBook = bookDao.observeBookById(1L).first()
        assertEquals("Updated Title", observedBook?.title)
    }

    @Test
    fun observeBookById_emitsNullWhenBookDeleted() = runTest {
        // Given
        bookDao.insertBook(sampleBook1)

        // When
        bookDao.deleteBookById(1L)

        // Then
        val observedBook = bookDao.observeBookById(1L).first()
        assertNull(observedBook)
    }

    // ==================== ADDITIONAL QUERY TESTS ====================

    @Test
    fun getFinishedBooksCount_returnsCorrectCount() = runTest {
        // Given
        bookDao.insertBooks(listOf(sampleBook1, sampleBook2, sampleBook4))
        // Add another finished book
        val finishedBook = sampleBook1.copy(id = 5L, pagesRead = 300)
        bookDao.insertBook(finishedBook)

        // When
        val count = bookDao.getFinishedBooksCount().first()

        // Then
        assertEquals(2, count) // Book 2 and Book 5
    }

    @Test
    fun getFinishedBooksCount_returnsZeroWhenNoFinishedBooks() = runTest {
        // Given
        bookDao.insertBook(sampleBook1) // Currently reading

        // When
        val count = bookDao.getFinishedBooksCount().first()

        // Then
        assertEquals(0, count)
    }

    @Test
    fun getTotalPagesRead_returnsCorrectSum() = runTest {
        // Given
        bookDao.insertBooks(listOf(sampleBook1, sampleBook2, sampleBook3, sampleBook4))

        // When
        val totalPages = bookDao.getTotalPagesRead().first()

        // Then
        // Book 1: 150, Book 2: 250, Book 3: 0 (not in library, not counted), Book 4: 0
        // Only library books count: 150 + 250 + 0 = 400
        assertEquals(400, totalPages)
    }

    @Test
    fun getTotalPagesRead_returnsZeroWhenNoBooksInLibrary() = runTest {
        // Given
        bookDao.insertBook(sampleBook3) // Not in library

        // When
        val totalPages = bookDao.getTotalPagesRead().first()

        // Then
        assertEquals(0, totalPages)
    }

    @Test
    fun getTotalPagesRead_returnsZeroWhenDatabaseEmpty() = runTest {
        // When
        val totalPages = bookDao.getTotalPagesRead().first()

        // Then
        assertEquals(0, totalPages)
    }

    // ==================== COMPLEX SCENARIO TESTS ====================

    @Test
    fun complexScenario_bookLifecycle() = runTest {
        // 1. Insert a new book (not in library)
        bookDao.insertBook(sampleBook3)
        var allBooks = bookDao.getAllBooks().first()
        assertEquals(1, allBooks.size)

        // 2. Add to library
        bookDao.updateLibraryStatus(3L, true)
        var libraryBooks = bookDao.getLibraryBooks().first()
        assertEquals(1, libraryBooks.size)

        // 3. Start reading
        bookDao.updateReadingProgress(3L, 100)
        var currentReads = bookDao.getCurrentReads().first()
        assertEquals(1, currentReads.size)

        // 4. Continue reading
        bookDao.updateReadingProgress(3L, 300)
        currentReads = bookDao.getCurrentReads().first()
        assertEquals(1, currentReads.size)

        // 5. Finish the book
        bookDao.updateReadingProgress(3L, 400)
        currentReads = bookDao.getCurrentReads().first()
        assertEquals(0, currentReads.size)

        val finishedBooks = bookDao.getFinishedBooks().first()
        assertEquals(1, finishedBooks.size)

        // 6. Add a personal note
        bookDao.updatePersonalNote(3L, "Excellent book!")
        val book = bookDao.getBookById(3L)
        assertEquals("Excellent book!", book?.personalNote)

        // 7. Remove from library
        bookDao.updateLibraryStatus(3L, false)
        libraryBooks = bookDao.getLibraryBooks().first()
        assertEquals(0, libraryBooks.size)

        // 8. Delete the book
        bookDao.deleteBookById(3L)
        allBooks = bookDao.getAllBooks().first()
        assertEquals(0, allBooks.size)
    }

    @Test
    fun complexScenario_multipleUsersReadingBooks() = runTest {
        // Given - Multiple books in different states
        bookDao.insertBooks(listOf(sampleBook1, sampleBook2, sampleBook3, sampleBook4))

        // Verify initial state
        assertEquals(4, bookDao.getAllBooks().first().size)
        assertEquals(3, bookDao.getLibraryBooks().first().size)
        assertEquals(1, bookDao.getCurrentReads().first().size)
        assertEquals(1, bookDao.getFinishedBooks().first().size)

        // User starts reading book 4
        bookDao.updateReadingProgress(4L, 100)
        assertEquals(2, bookDao.getCurrentReads().first().size)

        // User finishes book 1
        bookDao.updateReadingProgress(1L, 300)
        assertEquals(1, bookDao.getCurrentReads().first().size)
        assertEquals(2, bookDao.getFinishedBooks().first().size)

        // Verify statistics
        val totalPages = bookDao.getTotalPagesRead().first()
        assertEquals(650, totalPages) // 300 + 250 + 100

        val finishedCount = bookDao.getFinishedBooksCount().first()
        assertEquals(2, finishedCount)
    }
}

